### ISSUE TITLE
Add screenshots of the demo in the master readme

### ISSUE THREAD

**Issue by fvsch** [getkirby-v2/modules-plugin#10]
As a follow-up to #1, it would be nice to see one or several screenshots of how a page with modules can look like in the Panel and/or in a file explorer, near the top of the readme.md on the master branch. This would help new users understand what utility the plugin provides.

See https://github.com/TimOetting/kirby-builder for an example (though in that case I would put the image above the blueprint code).

**Comment by lukasbestle** [comment]
A screenshot of the Panel is difficult as the Modules plugin by itself does not have a GUI. But I see your point. Maybe a screenshot of the folder structure of a page using the demo modules would help. I will look into this for the next release.

**Comment by lukasbestle** [comment]
I wasn't able to find a screenshot that provides value to understand the plugin as the module folder structure is not very visual.

Let me know if you have an example screenshot.

**Comment by jenstornell** [comment]
I agree that a screenshot would be helpful even if it's just panel stuff. It took quite a while before I tried this plugin because I did not understand the purpose. For me and maybe other people it's easier to see something visually how it works, even in this case.

+1

**Comment by lukasbestle** [comment]
But that's the whole issue: There is no Panel stuff. :)

**Comment by jenstornell** [comment]
A simple page in the Panel containing '_modules' page in the sidebar and a simple module containing the '_modules' path. Maybe an animated gif when flipping them.
