### ISSUE TITLE
Visit the error page instead of redirect them, when not logged in

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/modules-plugin#14]
When inside the panel and preview a module it's great that it's redirected to actual page.

When not logged in it should not redirect, but instead visit the error page and set a 404 status code.

## Here is why:

A not logged person is a person that visit your site.

**If the visitor goes to:**
`example.com/parts/table` it should normally lead to an error page.

**If the visitor instead goes to:**
`example.com/modules/gallery` it should also lead to an error page.

A visitor will never see what is behind them. They are not and never will be visible for the user. To have a redirect on one of them does not make sense because of that reason.

## Solution:

Redirect when logged in. Visit error page + set status 404 when not logged in.

**Comment by lukasbestle** [comment]
Well, that's a bit of a subjective issue. I think it makes sense to redirect because the content that has been accessed has been "302 Found". Hence the redirect.

I understand that you don't like visitors to be able to see the internal structure of the site, but does it really matter?

**Comment by jenstornell** [comment]
I think it does matter, not leaving anything behind. But it's your plugin so it's your choice.

Anyway, it seems like a great plugin. I've been playing around with it a bit. Nice work in general. :)

**Comment by SirNovi** [comment]
I'm with jenstornell on this one. It doesn't make sense to me either to have a different approach. Wrong URLs should always lead to a 404. But then again. That URL should never appear anywhere anyhow, right?

**Comment by lukasbestle** [comment]
Yes and no.

Yes, the URL shouldn't appear anywhere.
No, module URLs are no "wrong URLs". In Kirby's world every page has a URL. Modules are Kirby pages. They are used for different things, but having them point to an error page could certainly cause confusion.

I will leave this open anyway, but to be honest I still think that "302 Found" describes the real situation quite well.
