### ISSUE TITLE
Modules ignores patterns config file

### ISSUE THREAD

**Issue by jakobploens** [getkirby-v2/modules-plugin#16]
When modules inside the patterns folder are called with the `$page->modules()` function, the default variables from the patterns config.php are beeing ignored. Is there a way to get this to work? I know that the plugins are two separate things, but maybe there is a way – otherwise I'll have to find dirty workarounds…

**Comment by lukasbestle** [comment]
That is true. The Modules plugin doesn't currently load the config file as it's a feature of the Patterns plugin.

However you are right that it might make sense to load the config file anyway and use the `defaults` array. I will consider this, until then you can [manually add this to this method](https://github.com/getkirby-plugins/modules-plugin/blob/master/lib/module.php#L72).
