### ISSUE TITLE
[Feature Request] Have a Panel Sidebar Section for Modules

### ISSUE THREAD

**Issue by luxlogica** [getkirby-v2/modules-plugin#20]
Please forgive me for the long post. The gist of what I'm going to say, is that IMHO "Modules" should have their own section in the Panel sidebar, just like Sub-Pages do. They need to have their *own* section, because although programatically they might be quite similar objects to Pages, for the user/developer they are **conceptually very different** to a sub-page - and mixing them up together in the interface is not helpful.

A Module, in this context, is a self-contained page section, with its own modular layout. We can think of pages as being composed of 'modules' (or 'sections'). So, if I have a site with a Home Page, an Online Catalog and a Blog, these pages might have the following Modules inside them:

![modules_diagram](https://user-images.githubusercontent.com/2994472/28749895-e3e5b75c-7519-11e7-9313-435dd8ad08d4.png)

For the developer, these Modules are totally **separate from Sub-Pages**. In our example site, we might have sub-pages like this:

![subpages_diagram](https://user-images.githubusercontent.com/2994472/28749910-6441997a-751a-11e7-9f67-b3e0d376109f.png)

Note that in many instances, a Page is likely to have *both* Modules and Sub-Pages - like in the case of our Catalog, or Blog above. Mixing both things under the same heading of 'Pages' in the Panel is confusing. Ideally, the Panel sidebar for the Blog above should look something like this:

![ideal_sidebar](https://user-images.githubusercontent.com/2994472/28749915-a801da08-751a-11e7-8d85-c521a0f2e965.png)

**Comment by lukasbestle** [comment]
I completely agree, that's what I wanted to do originally as well.

In Kirby 2, the Modules plugin is quite a hack and not a first-class citizen.
The new Panel in Kirby 3 will allow you to have a more flexible layout though.

We won't be able to change this in Kirby 2, but I will still keep this issue open as the idea itself is important.

Until then please take a look at the [Sortable plugin](https://github.com/lukaskleinschmidt/kirby-sortable) by @lukaskleinschmidt.
