### ISSUE TITLE
[Feature Request] ID-Based URL Routing for Modules

### ISSUE THREAD

**Issue by luxlogica** [getkirby-v2/modules-plugin#22]
Modules should not have a page-like URI, because they don't represent a page: they represent a section or part of a page. If I have a 'featuredproducts' module (= page section) inside a 'shop' page, then the expected, direct URL for that should be `http://example.com/shop#featuredproducts`.

Note that this means, that the module should trigger/load the controllers and models for itself, as well as for its parent. I believe this has a couple of implications for the entire routing mechanism in Kirby, as well as for how unique keys (for pages, and now modules) should be generated and checked.

**Comment by lukasbestle** [comment]
Please note that URL fragments (the part after the hash) are only a client-side feature. It doesn't make any difference in the routing, the fragment isn't even transmitted to the server.

**Comment by luxlogica** [comment]
Indeed, you are correct, @lukasbestle - the fragment part of the URL is not sent to the server, and is not available in the usual pre-defined variables, like `$_SERVER["REQUEST_URI"]`. 

I don't think this would be an issue, however, as in practice this only matters when loading modules' models and controllers, and these would be automatically loaded/triggered whenever the parent page is loaded anyway.

**Comment by lukasbestle** [comment]
Just wanted to let you know that this feature does not have any implications for Kirby's routing. :)

> This would only be an issue when dealing with modules such as 'Contact Form', or 'Blog List', which should be able to accept data and ajax requests directly, and independently from their parent page...

I have used the Modules plugin in a client project that had a "contact form" module using the Uniform plugin. It works just as expected if you call Uniform inside the module's snippet.

> The idea is to avoid having a URL such as http://example.com/shop/featuredproducts for a module...

This URL is never used anywhere anyway, so it doesn't really matter. Please note that we can't enforce fragment-based URLs. That only works if the developer adds the respective IDs in the markup.

**Comment by kraftner** [comment]
So I only cared about having the redirect adding the hash, so to stick with the above example redirecting
`http://example.com/shop/featuredproducts`
to
`http://example.com/shop#featuredproducts`

Unfortunately the template that does the redirect [is hardcoded](https://github.com/getkirby-plugins/modules-plugin/blob/7a6c80e62bcd7dbfb8692ffb12dd15bbb3503241/lib/module.php#L56). But we can fix that:

Create a plugin that has any name that is alphabetically after `modules`, so for example `modules-overwrite`. In that plugin you can then overwrite the template for a module.

`kirby()->set('template', 'module.featuredproducts', kirby()->roots()->site() . DS . 'modules' . DS . 'featuredproducts' . DS . 'template.php');`

Inside `template.php` you can then add

`go( $page->page() . '#' . $page->urlKey() );`.

This is just the bare-naked idea, but I guess from here you can go wild, e.g. make this handle multiple modules at once. Just thought I'd leave this here after I solved it for myself.

**Comment by lukasbestle** [comment]
Even simpler, you can put that template in the `site/templates` directory. Custom templates always override plugin templates. :)

**Comment by kraftner** [comment]
Maybe I misunderstood something but that doesn't work for me. And I also don't know how it should as the modules plugin forces the template to the internal plugin template to handle the redirect: https://github.com/getkirby-plugins/modules-plugin/blob/7a6c80e62bcd7dbfb8692ffb12dd15bbb3503241/lib/module.php#L56

**Comment by lukasbestle** [comment]
It does not *force* the template to the internal template, it just sets the template in the registry. And custom templates are always preferred over templates that have been registered in Kirby's registry.

Of course you need to have the template files for every module type. Please also verify that the redirect isn't cached by your browser.

**Comment by kraftner** [comment]
You're of course right. I didn't think of calling the file `module.featuredproducts.php`, always called it `featuredproducts.php` so it was ignored.

Still my approach offers the possibility to change the behaviour globally without the need to create duplicate templates for all modules by doing something like this:

```
$modules = Kirby\Modules\Modules::instance();
foreach($modules as $module){
	kirby()->set('template', $module->template, __DIR__ . DS . 'redirect.php');
}
```
