### ISSUE TITLE
Modules for Kirby3

### ISSUE THREAD

**Issue by findthebug** [getkirby-v2/modules-plugin#28]
Hello
Any plans integrate the modules plugin for kirby 3 ?

**Comment by harispepic** [comment]
@getkirby-plugins please update for kirby 3 🙏🏼

**Comment by frankziski** [comment]
i was disappionted as well when kirby 3 came out and the modules didnt work. 

BUT ANYWAY: They are now included directly into kirby 3. I found the solution inside the panel samples in the new refernce:

https://getkirby.com/docs/reference/panel/samples/one-pager

You store your former module-blueprints into the blueprints/pages folder and the templates into snippets. Blueprint-Fields are called as $part->headline() inside the snippets.

**Comment by findthebug** [comment]
There is also a builder plugin from tim: https://github.com/TimOetting/kirby-builder
I think this is more powerful as the parts one-page example, and comes close to the modules.
